services:
  php:
    build:
      context: .
      dockerfile: ComposerDockerfile
    container_name: foxentry_api_task_php
    volumes:
      - ./src:/code/src
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8080:8080"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: fox_entry_api_task_elasticsearch
    environment:
      - ELASTIC_PASSWORD=heslo
      - xpack.security.enabled=true
      - node.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  es_data:
    driver: local